name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-typecheck-build:
    name: Lint, Typecheck, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          npm ci --no-audit --no-fund || npm i --no-audit --no-fund

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc -b --pretty false --noEmit

      - name: Build
        run: npm run build

